[colors.bright]
black = "0x808080"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xFFFFFF"
yellow = "0xfeff00"

[colors.cursor]
cursor = "0xffffff"
text = "0xF81CE5"

[colors.normal]
black = "0x000000"
blue = "0x0066ff"
cyan = "0x00ffff"
green = "0x33ff00"
magenta = "0xcc00ff"
red = "0xfe0100"
white = "0xd0d0d0"
yellow = "0xfeff00"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[font]
size = 10

[font.bold]
family = "IosevkaTerm NF"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "IosevkaTerm NF"
style = "Oblique"

[font.normal]
family = "IosevkaTerm NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[hints.enabled]]
action = "Copy"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "Y"
mods = "Alt"

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
action = "PasteSelection"
key = "L"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[74;3u"
key = "J"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;3u"
key = "K"
mods = "Alt|Shift"

[window]
opacity = 0.75
