#!/bin/bash

sleep 0.5
xdotool key --clearmodifiers ctrl+a
xdotool key --clearmodifiers ctrl+super+k
xdotool key --clearmodifiers super+slash
sleep 0.8
xdotool key --clearmodifiers G bracketright space bracketright space G 0 quotedbl plus p
