#!/bin/sh
#exec stack ghc --stack-root $HOME/.xmonad/.stack -- \
stack ghc -- \
  --make xmonad.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -fwarn-tabs \
  -threaded \
  -O2 \
  -with-rtsopts=-N4 \
  -o "$1"

exec install xmonad-x86_64-linux ~/.xmonad/bin
