#!/usr/bin/env bash

# Simple wrapper around playerctl that pre-selects the target.
#
# Currently the rules are as follows:
# 1. If running, choose spotify.
# 2. Otherwise choose whatever.
#
# TODO: Investigate whether or not we can map chromium.instance<PID> to the
#       website being displayed. Currently, it points to the process running
#       the flash plugin.

target_priority=(
    spotify
    vlc
    "$(playerctl -l | head -n 1)"
)

for target in "${target_priority[@]}"; do
    player="$( playerctl -l | grep "${target}")" 2>/dev/null 

    if [ -n "${player}" ]; then
        exec playerctl -p "${player}" "${@}"
    fi
done

